In [ ]:
import numpy as np 
import pandas as pd 
import tensorflow as tf

In [ ]:
tf.__version__

'2.7.0'

In [ ]:
df = pd.read_csv('Churn_Modelling.csv') 
X = df.iloc[: , 3:-1].values
y = df.iloc[: , -1]

In [ ]:
print(X) 
X.shape

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]

(10000, 10)

In [ ]:
print(y)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values = np.nan , strategy = 'mean') 
X[: , 3:-1] = imputer.fit_transform(X[: , 3:-1])

In [ ]:
from sklearn.preprocessing import LabelEncoder 
lb = LabelEncoder()
X[:,2] = lb.fit_transform(X[:,2])

In [ ]:

print(X)

[[619 'France' 0 ... 1.0 1.0 101348.88]
 [608 'Spain' 0 ... 0.0 1.0 112542.58]
 [502 'France' 0 ... 1.0 0.0 113931.57]
 ...
 [709 'France' 0 ... 0.0 1.0 42085.58]
 [772 'Germany' 1 ... 1.0 0.0 92888.52]
 [792 'France' 0 ... 1.0 0.0 38190.78]]

In [ ]:
from sklearn.compose import ColumnTransformer 
import numpy as np
from sklearn.preprocessing import OneHotEncoder 
ct = ColumnTransformer(transformers = [('encoder' , OneHotEncoder(), [1])], remainder = 'passthrough') 
X = np.array(ct.fit_transform(X))

In [ ]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
lb1 = LabelEncoder()
df['Geography_label']=lb1.fit_transform(df['Geography'])
df

      RowNumber  CustomerId  ... Exited  Geography_label
0             1    15634602  ...      1                0
1             2    15647311  ...      0                2
2             3    15619304  ...      1                0
3             4    15701354  ...      0                0
4             5    15737888  ...      0                2
...         ...         ...  ...    ...              ...
9995       9996    15606229  ...      0                0
9996       9997    15569892  ...      0                0
9997       9998    15584532  ...      1                0
9998       9999    15682355  ...      1                1
9999      10000    15628319  ...      0                0

[10000 rows x 15 columns]

In [ ]:
df['Geography_label'].value_counts()

0    5014
1    2509
2    2477
Name: Geography_label, dtype: int64

In [ ]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [ ]:
add_columns = pd.get_dummies(df['Geography']) 
add_columns

      France  Germany  Spain
0          1        0      0
1          0        0      1
2          1        0      0
3          1        0      0
4          0        0      1
...      ...      ...    ...
9995       1        0      0
9996       1        0      0
9997       1        0      0
9998       0        1      0
9999       1        0      0

[10000 rows x 3 columns]

In [ ]:
df1 =df.join(add_columns)

In [ ]:
df.drop(['Geography'], axis =1 , inplace =True)

In [ ]:
df.drop(['Geography_label'], axis =1 , inplace = True)

In [ ]:
df1

      RowNumber  CustomerId    Surname  ...  France Germany Spain
0             1    15634602   Hargrave  ...       1       0     0
1             2    15647311       Hill  ...       0       0     1
2             3    15619304       Onio  ...       1       0     0
3             4    15701354       Boni  ...       1       0     0
4             5    15737888   Mitchell  ...       0       0     1
...         ...         ...        ...  ...     ...     ...   ...
9995       9996    15606229   Obijiaku  ...       1       0     0
9996       9997    15569892  Johnstone  ...       1       0     0
9997       9998    15584532        Liu  ...       1       0     0
9998       9999    15682355  Sabbatini  ...       0       1     0
9999      10000    15628319     Walker  ...       1       0     0

[10000 rows x 18 columns]

In [ ]:
columns_names = ['RowNumber' , 'CustomerId' ,'Surname', 'CreditScore' , 'Gender', 'Age', 'Tenure','Balance','NumOfProducts','NumOfProducts','IsActiveMember	','EstimatedSalary','France','Germany','Spain','Exited']

In [ ]:
df1 = df1.reindex(columns = columns_names)

In [ ]:
df1

      RowNumber  CustomerId    Surname  ...  Germany Spain  Exited
0             1    15634602   Hargrave  ...        0     0       1
1             2    15647311       Hill  ...        0     1       0
2             3    15619304       Onio  ...        0     0       1
3             4    15701354       Boni  ...        0     0       0
4             5    15737888   Mitchell  ...        0     1       0
...         ...         ...        ...  ...      ...   ...     ...
9995       9996    15606229   Obijiaku  ...        0     0       0
9996       9997    15569892  Johnstone  ...        0     0       0
9997       9998    15584532        Liu  ...        0     0       1
9998       9999    15682355  Sabbatini  ...        1     0       1
9999      10000    15628319     Walker  ...        0     0       0

[10000 rows x 16 columns]

In [ ]:
df1['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [ ]:
lb2 = LabelEncoder()
df1['Gender'] = lb2.fit_transform(df1['Gender'])

In [ ]:
df1

      RowNumber  CustomerId    Surname  ...  Germany  Spain  Exited
0             1    15634602   Hargrave  ...        0      0       1
1             2    15647311       Hill  ...        0      1       0
2             3    15619304       Onio  ...        0      0       1
3             4    15701354       Boni  ...        0      0       0
4             5    15737888   Mitchell  ...        0      1       0
...         ...         ...        ...  ...      ...    ...     ...
9995       9996    15606229   Obijiaku  ...        0      0       0
9996       9997    15569892  Johnstone  ...        0      0       0
9997       9998    15584532        Liu  ...        0      0       1
9998       9999    15682355  Sabbatini  ...        1      0       1
9999      10000    15628319     Walker  ...        0      0       0

[10000 rows x 16 columns]

In [ ]:
X = df1.iloc[:,3:-1]
y = df1.iloc[:,-1]

In [ ]:
print(X)

      CreditScore  Gender  Age  Tenure  ...  EstimatedSalary  France  Germany  Spain
0             619       0   42       2  ...        101348.88       1        0      0
1             608       0   41       1  ...        112542.58       0        0      1
2             502       0   42       8  ...        113931.57       1        0      0
3             699       0   39       1  ...         93826.63       1        0      0
4             850       0   43       2  ...         79084.10       0        0      1
...           ...     ...  ...     ...  ...              ...     ...      ...    ...
9995          771       1   39       5  ...         96270.64       1        0      0
9996          516       1   35      10  ...        101699.77       1        0      0
9997          709       0   36       7  ...         42085.58       1        0      0
9998          772       1   42       3  ...         92888.52       0        1      0
9999          792       0   28       4  ...         38190.78       1        0      0

[10000 rows x 12 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X ,y , test_size =0.2 , random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/extmath.py:986: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.7/dist-packages/sklearn/utils/extmath.py:991: RuntimeWarning: invalid value encountered in true_divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.7/dist-packages/sklearn/utils/extmath.py:1021: RuntimeWarning: invalid value encountered in true_divide
  new_unnormalized_variance -= correction ** 2 / new_sample_count

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense( units = 6 , activation = 'relu')) 
ann.add(tf.keras.layers.Dense(units = 6 , activation = 'relu')) 
ann.add(tf.keras.layers.Dense( units = 1 , activation = 'sigmoid'))

In [ ]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy']) 
ann.fit(X_train, y_train , batch_size =32 , epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 15/100
250/250 [==============================] - 0s 998us/step - loss: nan - accuracy: 0.7960
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 25/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 27/100
250/250 [==============================] - 0s 954us/step - loss: nan - accuracy: 0.7960
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 29/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 30/100
250/250 [==============================] - 0s 988us/step - loss: nan - accuracy: 0.7960
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 32/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 33/100
250/250 [==============================] - 0s 965us/step - loss: nan - accuracy: 0.7960
Epoch 34/100
250/250 [==============================] - 0s 996us/step - loss: nan - accuracy: 0.7960
Epoch 35/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 36/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 37/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 38/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 39/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 40/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 41/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 42/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 43/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 44/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 45/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 46/100
250/250 [==============================] - 0s 996us/step - loss: nan - accuracy: 0.7960
Epoch 47/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 48/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 49/100
250/250 [==============================] - 0s 995us/step - loss: nan - accuracy: 0.7960
Epoch 50/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 51/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 52/100
250/250 [==============================] - 0s 999us/step - loss: nan - accuracy: 0.7960
Epoch 53/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 54/100
250/250 [==============================] - 0s 941us/step - loss: nan - accuracy: 0.7960
Epoch 55/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 56/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 57/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 58/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 59/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 60/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 61/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 62/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 63/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 64/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 65/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 66/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 67/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 68/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 69/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 70/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 71/100
250/250 [==============================] - 0s 997us/step - loss: nan - accuracy: 0.7960
Epoch 72/100
250/250 [==============================] - 0s 998us/step - loss: nan - accuracy: 0.7960
Epoch 73/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 74/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 75/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 76/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 77/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 78/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 79/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 80/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 81/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 91/100
250/250 [==============================] - 0s 967us/step - loss: nan - accuracy: 0.7960
Epoch 92/100
250/250 [==============================] - 0s 930us/step - loss: nan - accuracy: 0.7960
Epoch 93/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 94/100
250/250 [==============================] - 0s 977us/step - loss: nan - accuracy: 0.7960
Epoch 95/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 96/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 97/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 98/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 99/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960
Epoch 100/100
250/250 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7960

In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

[[nan]]

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"

In [ ]:
y_pred = ann.predict(y_test)
print(np.concatenate((y_pred.reshape(len(y_pred) , 1), y_test.reshape(len(y_test),1))))

ValueError: ignored

In [2]:
from sklearn.metrics import confusion_matrix , accuracy_score 
cm = confusion_matrix(y_test , y_pred) 
print(cm) 
accuracy_score(y_test , y_pred)

NameError: ignored